window.MIDORI_CONFIG={SUPABASE_URL:"https://esiwwkphbqkqqcfelktn.supabase.co",SUPABASE_KEY:"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzaXd3a3BoYnFrcXFjZmVsa3RuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA2MDkwNTIsImV4cCI6MjEwNjE4NTA1Mn0.i1V9vbAbSWKGBcAx6ZZDg3uBfwhawJnUDDs9YSztMEk",ADMIN_EMAIL:"nana.udo@midori.fr"};
window.MIDORI_BUILD='anon-diagnostic-2026-09-29';
